#!/usr/bin/env node
// Writes the cards in index.html from their sources: content/<slug>.md for
// strategies, skills/<name>/SKILL.md for skills, agents/<name>/AGENTS.md with
// agents/<name>/card.md for agents. Only the block between the two markers in
// #list is touched; page, stylesheet and script stay as they are in the file.
// Node alone, no dependency. `node build.js` rewrites index.html,
// `node build.js --check` exits 1 when index.html is not what the sources give.

const fs = require("node:fs");
const path = require("node:path");

const ROOT = __dirname;
const PAGE = path.join(ROOT, "index.html");
const START = "      <!-- cards:start (generated by build.js from content/, skills/ and agents/; edit those, not this) -->";
const END = "      <!-- cards:end -->";
const LEVELS = ["Anfänger", "Mittel", "Fortgeschritten"];
const INDENT = "          ";

const errors = [];
const fail = (msg) => errors.push(msg);

const escape = (text) =>
  text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

// Frontmatter: a block of `key: value` lines between two `---` lines. Nested
// maps (SKILL.md metadata) are read one level deep, as `key.sub`.
function frontmatter(text, file) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { data: {}, body: text };
  const data = {};
  let parent = null;
  for (const line of m[1].split("\n")) {
    const nested = line.match(/^  ([\w-]+):\s*(.*)$/);
    const top = line.match(/^([\w-]+):\s*(.*)$/);
    if (nested && parent) data[`${parent}.${nested[1]}`] = nested[2].trim();
    else if (top) {
      parent = top[2].trim() === "" ? top[1] : null;
      data[top[1]] = top[2].trim();
    } else if (line.trim()) fail(`${file}: cannot read frontmatter line "${line}"`);
  }
  return { data, body: text.slice(m[0].length) };
}

// Inline Markdown: code spans, **strong**, *em* or _em_, [text](url), and a
// backslash before any of ` * _ [ ] \ keeps the character literal.
function inline(text) {
  const out = [];
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    if (c === "\\" && i + 1 < text.length && "`*_[]\\".includes(text[i + 1])) {
      out.push(escape(text[i + 1]));
      i += 2;
    } else if (c === "`") {
      const end = text.indexOf("`", i + 1);
      if (end < 0) { out.push("`"); i++; continue; }
      out.push(`<code>${escape(text.slice(i + 1, end))}</code>`);
      i = end + 1;
    } else if (text.startsWith("**", i)) {
      const end = text.indexOf("**", i + 2);
      if (end < 0) { out.push("**"); i += 2; continue; }
      out.push(`<strong>${inline(text.slice(i + 2, end))}</strong>`);
      i = end + 2;
    } else if ((c === "*" || c === "_") && text[i + 1] && !/\s/.test(text[i + 1])) {
      const end = text.indexOf(c, i + 1);
      if (end < 0) { out.push(escape(c)); i++; continue; }
      out.push(`<em>${inline(text.slice(i + 1, end))}</em>`);
      i = end + 1;
    } else if (c === "[") {
      const m = text.slice(i).match(/^\[([^\]]+)\]\(([^)\s]+)\)/);
      if (!m) { out.push("["); i++; continue; }
      out.push(`<a href="${escape(m[2])}">${inline(m[1])}</a>`);
      i += m[0].length;
    } else {
      out.push(escape(c));
      i++;
    }
  }
  return out.join("");
}

// Block Markdown, the subset the cards use: paragraphs, ## and ### headings
// (h4 and h5 on the card, one level below its title), - or * lists, 1. lists,
// > quotes, and fenced code. The fence `prompt` is the card's prompt block.
function blocks(lines, file, depth) {
  const html = [];
  let i = 0;
  const pad = INDENT + "  ".repeat(depth);
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }
    let m;
    if ((m = line.match(/^(`{3,})\s*(\S*)\s*$/))) {
      const fence = m[1];
      const lang = m[2];
      const body = [];
      i++;
      while (i < lines.length && lines[i] !== fence) body.push(lines[i++]);
      if (i >= lines.length) fail(`${file}: fenced block without a closing fence`);
      i++;
      const code = escape(body.join("\n"));
      if (lang === "prompt") html.push(`${pad}<pre class="prompt" tabindex="0">${code}</pre>`);
      else html.push(`${pad}<pre><code${lang ? ` class="language-${lang}"` : ""}>${code}\n</code></pre>`);
    } else if ((m = line.match(/^(#{1,6}) (.*)$/))) {
      const level = m[1].length;
      if (level < 2 || level > 3) fail(`${file}: headings are ## or ###, found "${line}"`);
      html.push(`${pad}<h${level + 2}>${inline(m[2].trim())}</h${level + 2}>`);
      i++;
    } else if (/^> ?/.test(line)) {
      const inner = [];
      while (i < lines.length && /^> ?/.test(lines[i])) inner.push(lines[i++].replace(/^> ?/, ""));
      html.push(`${pad}<blockquote>`, ...blocks(inner, file, depth), `${pad}</blockquote>`);
    } else if ((m = line.match(/^([-*]|\d+\.) /))) {
      const tag = /^\d/.test(m[1]) ? "ol" : "ul";
      const marker = tag === "ol" ? /^\d+\. / : /^[-*] /;
      html.push(`${pad}<${tag}>`);
      while (i < lines.length && marker.test(lines[i])) {
        let item = lines[i++].replace(marker, "");
        while (i < lines.length && /^\s{2,}\S/.test(lines[i])) item += " " + lines[i++].trim();
        html.push(`${pad}<li>${inline(item)}</li>`);
      }
      html.push(`${pad}</${tag}>`);
    } else {
      const para = [];
      while (i < lines.length && lines[i].trim() && !/^(#{1,6} |> ?|[-*] |\d+\. |`{3,})/.test(lines[i])) para.push(lines[i++].trim());
      html.push(`${pad}<p>${inline(para.join("\n"))}</p>`);
    }
  }
  return html;
}

const chips = (tags) =>
  tags.map((t) => `<li><button type="button" class="tag">${escape(t)}</button></li>`).join("");

function readTags(value, file) {
  const tags = (value || "").split(/\s+/).filter(Boolean);
  if (!tags.length) fail(`${file}: no tags`);
  for (const t of tags) if (t !== t.toLowerCase()) fail(`${file}: tag "${t}" is not lowercase`);
  return tags;
}

function strategy(file) {
  const slug = path.basename(file, ".md");
  const { data, body } = frontmatter(fs.readFileSync(path.join(ROOT, file), "utf8"), file);
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) fail(`${file}: the file name is the slug and must be lowercase letters, digits and hyphens`);
  for (const key of ["title", "level", "description"]) if (!data[key]) fail(`${file}: no ${key} in frontmatter`);
  if (!LEVELS.includes(data.level)) fail(`${file}: level must be one of ${LEVELS.join(", ")}`);
  const tags = readTags(data.tags, file);
  const details = blocks(body.split("\n"), file, 0);
  const prompts = details.filter((l) => l.includes('<pre class="prompt"')).length;
  if (prompts !== 1) fail(`${file}: exactly one \`\`\`prompt block, found ${prompts}`);
  return `      <article class="card" data-kind="strategy" id="${slug}" data-level="${data.level}" data-tags="${escape(tags.join(" "))}" itemscope itemtype="https://schema.org/HowTo">
        <header>
          <h3 itemprop="name"><a href="#${slug}">${escape(data.title)}</a></h3>
          <span class="level">${data.level}</span>
        </header>
        <p class="description" itemprop="description">${escape(data.description)}</p>
        <ul class="tags" itemprop="keywords">${chips(tags)}</ul>
        <details>
          <summary>Erklärung</summary>
${details.join("\n")}
        </details>
        <button type="button" class="button copy">Prompt kopieren</button>
      </article>`;
}

function standardCard({ kind, id, file, name, label, description, tags, text, itemtype }) {
  return `      <article class="card" data-kind="${kind}" id="${id}" data-file="${file}" data-tags="${escape(tags.join(" "))}" itemscope itemtype="${itemtype}">
        <header>
          <h3 itemprop="name"><a href="#${id}">${escape(name)}</a></h3>
          <span class="level">${label}</span>
        </header>
        <p class="description" itemprop="description">${escape(description)}</p>
        <ul class="tags" itemprop="keywords">${chips(tags)}</ul>
        <details>
          <summary>${path.basename(file)}</summary>
          <p class="caption">Liegt im Repo als <a class="file" href="https://github.com/pajew-ski/prompts/blob/main/${file}"><code>${file}</code></a>. Kopieren oder als Datei speichern; der Inhalt ist die Datei, byte für byte.</p>
          <pre class="prompt" tabindex="0">${escape(text)}</pre>
        </details>
        <div class="actions">
          <button type="button" class="button copy">${path.basename(file)} kopieren</button>
          <button type="button" class="button download" data-name="${path.basename(file)}">Als Datei</button>
        </div>
      </article>`;
}

function skill(dir) {
  const file = `skills/${dir}/SKILL.md`;
  const text = fs.readFileSync(path.join(ROOT, file), "utf8");
  const { data } = frontmatter(text, file);
  if (!data.name) fail(`${file}: no name in frontmatter`);
  else if (data.name !== dir) fail(`${file}: name "${data.name}" is not the directory "${dir}"`);
  else if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(dir) || dir.length > 64) fail(`${file}: name must be lowercase letters, digits and hyphens, at most 64 characters`);
  if (!data.description) fail(`${file}: no description in frontmatter`);
  else if (data.description.length > 1024) fail(`${file}: description longer than 1024 characters`);
  return standardCard({
    kind: "skill", id: `skill-${dir}`, file, name: dir, label: "Skill",
    description: data.description || "", tags: readTags(data["metadata.tags"], file), text,
    itemtype: "https://schema.org/SoftwareSourceCode",
  });
}

function agent(dir) {
  const file = `agents/${dir}/AGENTS.md`;
  const card = `agents/${dir}/card.md`;
  const text = fs.readFileSync(path.join(ROOT, file), "utf8");
  if (!fs.existsSync(path.join(ROOT, card))) { fail(`${card}: missing; it holds the card's description and tags`); return ""; }
  const { data } = frontmatter(fs.readFileSync(path.join(ROOT, card), "utf8"), card);
  if (!data.description) fail(`${card}: no description in frontmatter`);
  return standardCard({
    kind: "agent", id: `agent-${dir}`, file, name: dir, label: "Agent",
    description: data.description || "", tags: readTags(data.tags, card), text,
    itemtype: "https://schema.org/TechArticle",
  });
}

const dirs = (name) => (fs.existsSync(path.join(ROOT, name)) ? fs.readdirSync(path.join(ROOT, name)).filter((d) => !d.startsWith(".")).sort() : []);
const cards = [
  ...dirs("content").filter((f) => f.endsWith(".md")).map((f) => strategy(`content/${f}`)),
  ...dirs("skills").map(skill),
  ...dirs("agents").map(agent),
];

const page = fs.readFileSync(PAGE, "utf8");
const start = page.indexOf(START);
const end = page.indexOf(END);
if (start < 0 || end < 0 || end < start) fail("index.html: the cards:start and cards:end markers are missing");
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const next = page.slice(0, start + START.length) + "\n" + cards.join("\n") + "\n" + page.slice(end);
if (process.argv.includes("--check")) {
  if (next !== page) {
    console.error("index.html is not what content/, skills/ and agents/ give; run `node build.js` and commit the result");
    process.exit(1);
  }
  console.log(`index.html matches its ${cards.length} sources`);
} else {
  if (next !== page) fs.writeFileSync(PAGE, next);
  console.log(`${cards.length} cards written to index.html`);
}
