server {
    listen 8099 default_server;
    listen [::]:8099 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(css|js|svg|json|ttl|jsonld)$ {
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }
}
